language: haskell
install:
  - cd tests
  - nvm install 0.12
  - cabal install elm-make
  - cabal install elm-package
  - npm install -g elm-test
  - elm-package install -y
script: elm-test ConsoleRunner.elm
